# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='If you have used topic make sureto input it here', null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Topic'),
        ),
    ]
