# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20170907_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='If you have used topic make sureto input it here', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tutorial.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text='High Level: Python or Ruby or ROR', max_length=255, unique=True),
        ),
    ]
