# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20170918_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='tutorial.Category'),
        ),
    ]
