# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 03:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_auto_20171028_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
